#!/bin/bash
#BSUB -W 23:59
#BSUB -n 12
#BSUB -M 64
#BSUB -R rusage[mem=64]
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/logs
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/logs
#BSUB -q medium


### --- Setup --- ###

source /etc/profile.d/modules.sh
eval "$(/risapps/rhel8/miniforge3/24.5.0-0/bin/conda shell.bash hook)"

cd /rsrch5/scratch/epi/${USER}/GTEx_v8

THREADS=12
LIBID="${FILE%%.*}"
DIR_BAM=/rsrch3/scratch/reflib/GTEx/SourceFiles/Bam

mkdir -p raw/${TISSUE}
mkdir -p align/${TISSUE}
mkdir -p quant/${TISSUE}


### --- Pull fastqs --- ###
  
if [ "$PULL" = TRUE ]; then

    conda activate samtools-1.16.1
    
    rm raw/${TISSUE}/*${LIBID}*.bam
    
    samtools sort -n -@ ${THREADS} -o raw/${TISSUE}/${LIBID}_sorted.bam ${DIR_BAM}/${FILE}
    
    samtools fastq -@ ${THREADS} \
      -1 raw/${TISSUE}/${LIBID}_R1.fastq.gz \
      -2 raw/${TISSUE}/${LIBID}_R2.fastq.gz \
      -0 /dev/null -s /dev/null \
      -n raw/${TISSUE}/${LIBID}_sorted.bam
      
    rm raw/${TISSUE}/${LIBID}_sorted.bam
    
    conda deactivate
  
fi


### --- Align to genome with STAR --- ###

if [ "$ALIGN" = TRUE ]; then

  # Align reads to transcriptome with star
  conda activate star-2.7.4a
  rm -rf temp/${TISSUE}/${LIBID} # delete temp directory (STAR will remake)

  TXINDEX_star=/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/star-2.7.4a_GCA_000001405.15_GRCh38_no_alt_analysis_set

  STAR --genomeDir ${TXINDEX_star} \
       --readFilesIn raw/${TISSUE}/${LIBID}_R1.fastq.gz raw/${TISSUE}/${LIBID}_R2.fastq.gz \
       --readFilesCommand zcat --runThreadN ${THREADS} \
       --genomeLoad NoSharedMemory --outFilterMultimapNmax 20 \
       --alignSJoverhangMin 8 --alignSJDBoverhangMin 1 \
       --outFilterMismatchNmax 999 --outFilterMismatchNoverReadLmax 0.04 \
       --alignIntronMin 20 --alignIntronMax 1000000 \
       --alignMatesGapMax 1000000 --outSAMheaderHD @HD VN:1.4 SO:coordinate \
       --outSAMunmapped Within --outFilterType BySJout \
       --outSAMattributes NH HI AS NM MD --outSAMtype BAM Unsorted \
       --sjdbScore 1 --outTmpDir temp/${TISSUE}/${LIBID} \
       --outFileNamePrefix align/${TISSUE}/${LIBID} \
       --twopassMode Basic

  conda deactivate
  
  rm -rf align/${TISSUE}/${LIBID}_STARgenome 
  rm -rf align/${TISSUE}/${LIBID}_STARpass1 
  rm -rf temp/${TISSUE}/${LIBID}

fi


### --- featureCounts --- ###

if [ "$FEATURECOUNTS" = TRUE ]; then

  module load subread
  
  for VERSION in GENCODE_v27 GENCODE_v38 GENCODE_v45 Ensembl; do
  
      fc_out=/rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/${VERSION}/${TISSUE}/featureCounts
      mkdir -p $fc_out
      
      featureCounts \
        -a /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/fc_annots/${VERSION}_genes.saf \
        -F SAF \
        -o ${fc_out}/${LIBID}_gene.txt \
        -p \
        --countReadPairs \
        align/${TISSUE}/${LIBID}Aligned.out.bam \
        -T 12
      
      featureCounts \
        -a /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/fc_annots/${VERSION}_transcripts.saf \
        -F SAF \
        -o ${fc_out}/${LIBID}_transcript.txt \
        -p \
        --countReadPairs \
        -O \
        align/${TISSUE}/${LIBID}Aligned.out.bam \
        -T 12
    
  done
  
  rm -v align/${TISSUE}/${LIBID}*

fi


### --- RSEM --- ###

if [ "$RSEM" = TRUE ]; then

  conda activate rsem-1.3.3
  
  for VERSION in GENCODE_v27 GENCODE_v38 GENCODE_v45 Ensembl; do
  
    declare -A TXINDEX_MAP
    TXINDEX_MAP[GENCODE_v27]=/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v27_rsem/rsem
    TXINDEX_MAP[GENCODE_v38]=/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v38_rsem/rsem
    TXINDEX_MAP[GENCODE_v45]=/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v45_rsem/rsem
    TXINDEX_MAP[Ensembl]=/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/ensembl_rsem/rsem
    
      TXINDEX=${TXINDEX_MAP[$VERSION]}
  
      # Make sure the output directory exists
      DIR_OUT_RSEM=/rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/${VERSION}/${TISSUE}/RSEM
      mkdir -p ${DIR_OUT_RSEM}
      
      DIR_OUT_RSEM_TEMP=quant/${TISSUE}/${VERSION}/RSEM
      mkdir -p ${DIR_OUT_RSEM_TEMP}
  
      # Run RSEM + STAR quantification
      rsem-calculate-expression \
          --star \
          --star-gzipped-read-file \
          --star-path /risapps/rhel8/miniforge3/24.5.0-0/envs/star-2.7.4a/bin \
          --strandedness none \
          -p ${THREADS} \
          --no-bam-output \
          --paired-end \
          raw/${TISSUE}/${LIBID}_R1.fastq.gz \
          raw/${TISSUE}/${LIBID}_R2.fastq.gz \
          ${TXINDEX} \
          ${DIR_OUT_RSEM_TEMP}/${LIBID}
          
      mv ${DIR_OUT_RSEM_TEMP}/${LIBID}.isoforms.results ${DIR_OUT_RSEM}/${LIBID}.isoforms.results
      chmod g+r ${DIR_OUT_RSEM}/${LIBID}.isoforms.results
      
      mv ${DIR_OUT_RSEM_TEMP}/${LIBID}.genes.results ${DIR_OUT_RSEM}/${LIBID}.genes.results
      chmod g+r ${DIR_OUT_RSEM}/${LIBID}.genes.results
         
      rm ${DIR_OUT_RSEM_TEMP}/*${LIBID}*.bam
      rm ${DIR_OUT_RSEM_TEMP}/${LIBID}.temp/*${LIBID}*.bam

  done

  conda deactivate

fi


### --- Kallisto --- ###

if [ "$KALLISTO" = TRUE ]; then

  eval "$(/risapps/rhel8/miniforge3/24.5.0-0/bin/conda shell.bash hook)"
  conda activate kallisto-0.48.0

  # Define KALLISTO index paths for each version
  declare -A KALLISTO_INDEX_MAP
  KALLISTO_INDEX_MAP[GENCODE_v27]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v27/kallisto_index/GENCODE_v27"
  KALLISTO_INDEX_MAP[GENCODE_v38]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v38/kallisto_index/GENCODE_v38"
  KALLISTO_INDEX_MAP[GENCODE_v45]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v45/kallisto_index/GENCODE_v45"
  KALLISTO_INDEX_MAP[Ensembl]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/Ensembl/kallisto_index/Ensembl"

  for VERSION in GENCODE_v27 GENCODE_v38 GENCODE_v45 Ensembl; do

      INDEX=${KALLISTO_INDEX_MAP[$VERSION]}
      DIR_OUT_QUANT=/rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/${VERSION}/${TISSUE}/kallisto
      mkdir -p "$DIR_OUT_QUANT"

      kallisto quant \
        -i "$INDEX" \
        -o "${DIR_OUT_QUANT}/${LIBID}" \
        -t ${THREADS} \
        raw/${TISSUE}/${LIBID}_R1.fastq.gz \
        raw/${TISSUE}/${LIBID}_R2.fastq.gz

  done

  conda deactivate

fi


### --- Salmon --- ###

if [ "$SALMON" = TRUE ]; then

  conda activate salmon-1.10.2

  # Define TXINDEX paths for each version
  declare -A TXINDEX_MAP
  TXINDEX_MAP[GENCODE_v27]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode_v27/salmon/gencode_v27"
  TXINDEX_MAP[GENCODE_v38]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode.v38.salmon_index"
  TXINDEX_MAP[GENCODE_v45]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/gencode.v45.salmon_index/gencode_v45"
  TXINDEX_MAP[Ensembl]="/rsrch5/home/epi/bhattacharya_lab/data/GenomicReferences/txome/Ensembl/salmon/Ensembl"

  for VERSION in GENCODE_v27 GENCODE_v38 GENCODE_v45 Ensembl; do

      TXINDEX=${TXINDEX_MAP[$VERSION]}
      DIR_OUT_QUANT=/rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/${VERSION}/${TISSUE}/salmon
      mkdir -p "$DIR_OUT_QUANT"

      salmon quant \
        -i "$TXINDEX" --libType A \
        --validateMappings --seqBias \
        -p ${THREADS} \
        -1 raw/${TISSUE}/${LIBID}_R1.fastq.gz \
        -2 raw/${TISSUE}/${LIBID}_R2.fastq.gz \
        -o ${DIR_OUT_QUANT}/${LIBID}

  done

  conda deactivate

fi


### --- Remove fastqs --- ###

if [ "$PULL" = TRUE ]; then
  rm raw/${TISSUE}/${LIBID}_R1.fastq.gz raw/${TISSUE}/${LIBID}_R2.fastq.gz
fi