#!/bin/bash
#BSUB -W 8:00
#BSUB -n 12
#BSUB -M 200
#BSUB -R rusage[mem=200]
#BSUB -o /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/logs
#BSUB -e /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/logs
#BSUB -q medium

mkdir -p /rsrch5/home/epi/${USER}/scratch/GTEx_v8/tximeta

cd /rsrch5/home/epi/bhattacharya_lab/data/GTEx_v8/requants/Scripts

singularity exec --bind /rsrch5 /risapps/singularity/repo/RStudio/4.3.1/rstudio_4.3.1.sif Rscript quants_GR.R ${TISSUE} ${USER}